import React, { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};

const translations = {
  vi: {
    // Navigation
    dashboard: 'Dashboard',
    medicalHistoryNav: 'Lịch sử bệnh lý',
    medicalNews: 'Tin tức y tế',
    medicalNewsDescription: 'Cập nhật tin tức y tế mới nhất và thông tin sức khỏe',
    fitness: 'Rèn Luyện',
    reminders: 'Nhắc nhở',
    chatbot: 'Chatbot',
    profile: 'Hồ sơ cá nhân',
    settings: 'Cài đặt',
    logout: 'Đăng xuất',
    chat: 'Trò chuyện',

    // Common
    welcome: 'Chào mừng',
    search: 'Tìm kiếm bài tập, lời nhắc, mẹo sức khỏe...',
    save: 'Lưu',
    cancel: 'Hủy',
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    add: 'Thêm',
    update: 'Cập nhật',
    create: 'Tạo mới',
    close: 'Đóng',
    confirm: 'Xác nhận',
    back: 'Quay lại',
    next: 'Tiếp theo',
    loading: 'Đang tải...',
    noData: 'Không có dữ liệu',
    total: 'Tổng',
    today: 'Hôm nay',
    thisWeek: 'Tuần này',
    thisMonth: 'Tháng này',
    all: 'Tất cả',
    filter: 'Lọc',
    sort: 'Sắp xếp',

    // Medical News
    featuredNews: 'Tin tức nổi bật',
    allNews: 'Tất cả tin tức',
    allCategories: 'Tất cả danh mục',
    fitnessCategory: 'Thể thao',
    diabetesCategory: 'Tiểu đường',
    mentalHealthCategory: 'Sức khỏe tâm thần',
    technologyCategory: 'Công nghệ',
    nutritionCategory: 'Dinh dưỡng',
    vaccinesCategory: 'Vắc xin',
    searchNews: 'Tìm kiếm tin tức...',
    latest: 'Mới nhất',
    oldest: 'Cũ nhất',
    readTime: 'Thời gian đọc',
    readMore: 'Đọc thêm',
    articles: 'bài viết',
    noNewsFound: 'Không tìm thấy tin tức',
    tryDifferentSearch: 'Thử tìm kiếm với từ khóa khác',
    dataLoadError: 'Lỗi tải dữ liệu',
    tryAgain: 'Thử lại',
    updatenew: 'Cập nhật tin tức sức khỏe và công nghệ y khoa mới nhất',

    // Dashboard
    vitalSigns: 'Chỉ số sống',
    systolic: 'Tâm thu',
    diastolic: 'Tâm trương',
    heartRate: 'Nhịp tim',
    weight: 'Cân nặng',
    todayReminders: 'Nhắc nhở hôm nay',
    recentActivity: 'Hoạt động gần đây',
    healthOverview: 'Tổng quan sức khỏe',
    patientSummary: 'Tóm tắt bệnh nhân',
    systolicAnalysis: 'Phân tích tâm thu',
    ecgMonitoring: 'Giám sát ECG',
    bpm: 'BPM',
    mmHg: 'mmHg',
    kg: 'kg',
    years: 'tuổi',
    cm: 'cm',
    viewDetails: 'Xem chi tiết',
    searchHistory: 'Tìm kiếm lịch sử',
    startPract: 'Bắt đầu tập',
    viewALL: 'Xem tất cả',
    // Fitness
    workouts: 'Bài tập',
    exercises: 'Tập luyện',
    progress: 'Tiến trình',
    duration: 'Thời gian',
    calories: 'Calo',
    start: 'Bắt đầu',
    complete: 'Hoàn thành',
    completed: 'Đã hoàn thành',
    inProgress: 'Đang thực hiện',
    myWorkouts: 'Bài tập của tôi',
    workoutPlans: 'Kế hoạch tập luyện',
    level: 'Cấp độ',
    beginner: 'Mới bắt đầu',
    intermediate: 'Trung bình',
    advanced: 'Nâng cao',
    category: 'Danh mục',
    cardio: 'Cardio',
    strength: 'Sức mạnh',
    flexibility: 'Linh hoạt',
    yoga: 'Yoga',
    hiit: 'HIIT',
    weeklyProgress: 'Tiến trình tuần',
    totalWorkouts: 'Tổng bài tập',
    totalMinutes: 'Tổng phút đã tập',
    caloriesBurned: 'Calo đốt cháy',
    minutesExc: 'Phút tập luyện',
    avgScore: 'Tổng điểm TB',
    searchExc: '     Tìm kiếm bài tập...',
    weekgoal: 'Mục tiêu tuần này',

    // Reminders
    medication: 'Thuốc',
    exercise: 'Tập thể dục',
    bedtime: 'Giấc ngủ',
    time: 'Thời gian',
    enabled: 'Đã bật',
    disabled: 'Đã tắt',
    myReminders: 'Nhắc nhở của tôi',
    upcomingReminders: 'Sắp tới',
    pastReminders: 'Đã qua',
    activeReminders: 'Đang hoạt động',
    reminderType: 'Loại nhắc nhở',
    reminderTime: 'Thời gian nhắc',
    reminderMessage: 'Nội dung',
    createReminder: 'Tạo nhắc nhở',
    editReminder: 'Sửa nhắc nhở',
    deleteReminder: 'Xóa nhắc nhở',
    reminderTitle: 'Tiêu đề',
    reminderDescription: 'Mô tả',
    selectDate: 'Chọn ngày',
    selectTime: 'Chọn giờ',
    repeat: 'Lặp lại',
    daily: 'Hằng ngày',
    weekly: 'Hằng tuần',
    monthly: 'Hằng tháng',
    never: 'Không lặp',
    noReminder: 'Không có nhắc nhở nào cho ngày này',
    general: 'Chung',
    allReminders: 'Tất cả nhắc nhở',
    more: 'thêm',
    // Chatbot
    aiAssistant: 'Trợ lý AI',
    healthAssistant: 'Trợ lý sức khỏe',
    askMeAnything: 'Hỏi tôi bất cứ điều gì',
    typeMessage: 'Nhập tin nhắn...',
    send: 'Gửi',
    quickQuestions: 'Câu hỏi nhanh',
    chatHistory: 'Lịch sử trò chuyện',
    clearChat: 'Xóa cuộc trò chuyện',
    suggestedQuestions: 'Câu hỏi gợi ý',
    noticalAI: 'AI có thể mắc lỗi. Hãy tham khảo bác sĩ khi cần.',
    note1: 'Tôi nên tập cardio bao lâu mỗi ngày?',
    note2: 'Gợi ý lịch uống thuốc hợp lý?',
    note3: 'Chế độ ăn để giảm cân an toàn?',
    note4: 'Mẹo ngủ ngon và đúng giờ?',
    

    // Profile
    personalInfo: 'Thông tin cá nhân',
    healthInfo: 'Thông tin sức khỏe',
    firstName: 'Họ',
    lastName: 'Tên',
    email: 'Email',
    phone: 'Số điện thoại',
    address: 'Địa chỉ',
    age: 'Tuổi',
    gender: 'Giới tính',
    bloodGroup: 'Nhóm máu',
    height: 'Chiều cao',
    changePassword: 'Đổi mật khẩu',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Xác nhận mật khẩu',
    male: 'Nam',
    female: 'Nữ',
    other: 'Khác',
    selectBloodGroup: 'Chọn nhóm máu',
    enterHeight: 'Nhập chiều cao',
    enterWeight: 'Nhập cân nặng',
    enterPhone: 'Nhập số điện thoại',
    enterAddress: 'Nhập địa chỉ',
    active: 'Hoạt động',
    myProfile: 'Hồ sơ của tôi',

    // Settings
    appearance: 'Giao diện',
    language: 'Ngôn ngữ',
    notifications: 'Thông báo',
    theme: 'Theme',
    lightMode: 'Sáng',
    darkMode: 'Tối',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    themeDescription: 'Chuyển đổi giữa light và dark mode',
    notificationPreferences: 'Tùy chọn thông báo',
    medicationReminders: 'Nhắc nhở uống thuốc và tập luyện',
    workoutNotifications: 'Hoàn thành bài tập',
    measurementNotifications: 'Cập nhật chỉ số sức khỏe',
    aiSuggestions: 'Gợi ý từ AI chatbot',
    dangerZone: 'Vùng nguy hiểm',
    deleteAccount: 'Xóa tài khoản',
    deleteAccountWarning: 'Xóa toàn bộ dữ liệu cá nhân của bạn. Hành động này không thể hoàn tác.',
    customizeExperience: 'Tùy chỉnh trải nghiệm của bạn',

    // Notifications
    notificationCenter: 'Trung tâm thông báo',
    markAsRead: 'Đánh dấu đã đọc',
    clearAll: 'Xóa tất cả',
    noNotifications: 'Chưa có thông báo',
    yourActivitiesHere: 'Các hoạt động của bạn sẽ xuất hiện ở đây',

    // Medical History
    medicalHistory: {
      title: 'Lịch sử bệnh lý',
      subtitle: 'Theo dõi và quản lý lịch sử y tế của bạn',
      listTitle: 'Danh sách lịch sử y tế',
      addNew: 'Thêm mới',
      addFirst: 'Thêm lịch sử đầu tiên',
      addTitle: 'Thêm lịch sử y tế mới',
      editTitle: 'Chỉnh sửa lịch sử y tế',
      date: 'Ngày',
      day: 'Ngày',
      titleLabel: 'Tiêu đề',
      notes: 'Ghi chú',
      titlePlaceholder: 'Ví dụ: Khám sức khỏe tổng quát',
      notesPlaceholder: 'Mô tả chi tiết về tình trạng sức khỏe, kết quả khám, đơn thuốc...',
      cancel: 'Hủy',
      add: 'Thêm',
      update: 'Cập nhật',
      confirmDelete: 'Bạn có chắc chắn muốn xóa mục này?',
      noData: 'Chưa có lịch sử y tế nào',
      total: 'Tổng số',
      completed: 'Hoàn thành',
      ongoing: 'Đang điều trị',
      resolved: 'Đã khỏi',
      unknown: 'Chưa xác định',
      surgery: 'Phẫu thuật',
      checkup: 'Khám sức khỏe tổng quát',
      vaccination: 'Tiêm phòng cúm',
      headache: 'Đau đầu kéo dài',
      allergy: 'Dị ứng thời tiết',
      surgeryDetail: 'Phẫu thuật ruột thừa',
      checkupNotes: 'Kết quả khám sức khỏe định kỳ. Tất cả các chỉ số đều bình thường. Khuyến nghị duy trì chế độ ăn uống và tập luyện hiện tại.',
      vaccinationNotes: 'Đã tiêm phòng cúm mùa 2024-2025. Không có phản ứng phụ. Cần tiêm lại vào năm sau.',
      headacheNotes: 'Đau đầu trong 3 ngày liên tiếp. Đã uống thuốc giảm đau nhưng không hiệu quả. Cần theo dõi thêm.',
      allergyNotes: 'Triệu chứng: hắt hơi, chảy nước mũi, ngứa mắt. Đã dùng thuốc kháng histamine. Tránh tiếp xúc với phấn hoa.',
      surgeryNotes: 'Phẫu thuật nội soi cắt ruột thừa. Quá trình phẫu thuật thành công. Thời gian hồi phục: 2 tuần.',
      typeCheckup: 'Khám sức khỏe',
      typeVaccination: 'Tiêm phòng',
      typeSymptom: 'Triệu chứng',
      typeAllergy: 'Dị ứng',
      typeSurgery: 'Phẫu thuật',
      typeOther: 'Khác',
      viewAll: 'Xem lịch sử bệnh lý'
    },

    // Auth
    login: 'Đăng nhập',
    signIn: 'Đăng nhập ngay',
    register: 'Đăng ký',
    createAccount: 'Tạo tài khoản mới',
    createAcc: 'Đăng ký',
    welcomeBack: 'Chào mừng trở lại',
    welcomeToHealthManager: 'Chào mừng đến với Health Manager',
    loginToContinue: 'Đăng nhập để tiếp tục quản lý sức khỏe của bạn',
    dontHaveAccount: 'Bạn chưa có tài khoản?',
    alreadyHaveAccount: 'Bạn đã có tài khoản?',
    joinHealthManager: 'Tham gia Health Manager',
    forgotPassword: 'Quên mật khẩu?',
    rememberMe: 'Ghi nhớ đăng nhập',
    enterEmail: 'Nhập email',
    enterPassword: 'Nhập mật khẩu',
    enterFirstName: 'Nhập họ',
    enterLastName: 'Nhập tên',
    selectGender: 'Chọn giới tính',
    Password: 'Mật khẩu',

    // Registration validation
    firstNameRequired: 'Vui lòng nhập họ',
    lastNameRequired: 'Vui lòng nhập tên',
    emailRequired: 'Vui lòng nhập email',
    passwordRequired: 'Vui lòng nhập mật khẩu',
    confirmPasswordRequired: 'Vui lòng xác nhận mật khẩu',
    ageRequired: 'Vui lòng nhập tuổi',
    genderRequired: 'Vui lòng chọn giới tính',
    invalidEmail: 'Email không hợp lệ',
    passwordMinLength: 'Mật khẩu phải có ít nhất 6 ký tự',
    passwordsDoNotMatch: 'Mật khẩu không khớp',
    ageMin: 'Tuổi phải lớn hơn 0',
    ageMax: 'Tuổi phải nhỏ hơn 120',
    registrationSuccess: 'Đăng ký thành công!',
    registrationError: 'Lỗi đăng ký',
    invalidAge: 'Tuổi không hợp lệ!',
    inputAge: 'Nhập tuổi',
    // Social login
    orContinueWith: 'Hoặc tiếp tục với',
    or: 'Hoặc',
    continueWithGoogle: 'Tiếp tục với Google',
    continueWithFacebook: 'Tiếp tục với Facebook',
    googleLoginComingSoon: 'Đăng nhập Google sẽ có sớm',
    facebookLoginComingSoon: 'Đăng nhập Facebook sẽ có sớm',
    
    completed: 'Hoàn thành',
    caloriesBurned: 'Calo đốt cháy',
    minutesTrained: 'Phút tập luyện',
    avgRating: 'Đánh giá TB',
    myWorkouts: 'Bài tập của tôi',
    show: 'Hiển thị:',
    fitnessExplore: 'Khám phá và theo dõi tiến trình tập luyện của bạn',
    caloriesIsBurned: 'Tổng calo đã đốt',

    deleteReminderConfirmation: 'Xóa nhắc nhở này?',
    noUpcomingReminders: 'Không có nhắc nhở nào sắp tới.',
    startDate: 'Ngày bắt đầu',
    endDate: 'Ngày kết thúc',
    editRecurringEventWarning: 'Lưu ý: Chỉnh sửa một sự kiện lặp sẽ tách nó ra khỏi chuỗi.',
    deleteRecurringReminderTitle: 'Xóa nhắc nhở lặp',
    deleteRecurringReminderPrompt: 'Bạn có chắc muốn xóa nhắc nhở',
    deleteAllOccurrences: 'Xóa tất cả chuỗi nhắc nhở',
    deleteThisOccurrenceOnly: 'Chỉ xóa lần này',
  
  },
  en: {

    
    
    myWorkouts: 'My Workouts',
    show: 'Show:',
    fitnessExplore: 'Explore and track your workout progress',
    // Navigation
    dashboard: 'Dashboard',
    medicalHistoryNav: 'Medical History',
    medicalNews: 'Medical News',
    medicalNewsDescription: 'Stay updated with the latest medical news and health information',
    fitness: 'Fitness',
    reminders: 'Reminders',
    chatbot: 'Chatbot',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    chat: 'Chat',
    // Common
    welcome: 'Welcome',
    search: 'Search workouts, reminders, health tips...',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    update: 'Update',
    create: 'Create',
    close: 'Close',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    loading: 'Loading...',
    noData: 'No data',
    total: 'Total',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    all: 'All',
    filter: 'Filter',
    sort: 'Sort',

    // Medical News
    featuredNews: 'Featured News',
    allNews: 'All News',
    allCategories: 'All Categories',
    fitnessCategory: 'Fitness',
    diabetesCategory: 'Diabetes',
    mentalHealthCategory: 'Mental Health',
    technologyCategory: 'Technology',
    nutritionCategory: 'Nutrition',
    vaccinesCategory: 'Vaccines',
    searchNews: 'Search news...',
    latest: 'Latest',
    oldest: 'Oldest',
    readTime: 'Read Time',
    readMore: 'Read More',
    articles: 'articles',
    noNewsFound: 'No news found',
    tryDifferentSearch: 'Try a different search term',
    dataLoadError: 'Data loading error',
    tryAgain: 'Try Again',
    updatenew: 'Update the latest health news and medical technology',

    // Dashboard
    vitalSigns: 'Vital Signs',
    systolic: 'Systolic',
    diastolic: 'Diastolic',
    heartRate: 'Heart Rate',
    weight: 'Weight',
    todayReminders: 'Today\'s Reminders',
    recentActivity: 'Recent Activity',
    healthOverview: 'Health Overview',
    patientSummary: 'Patient Summary',
    systolicAnalysis: 'Systolic Analysis',
    ecgMonitoring: 'ECG Monitoring',
    bpm: 'BPM',
    mmHg: 'mmHg',
    kg: 'kg',
    years: 'years old',
    cm: 'cm',
    viewDetails: 'View details',
    medicalHistory: 'Medical History',
    searchHistory: 'Search History',
    startPract: 'Start Practiting',
    viewALL: 'View All',


    // Fitness
    workouts: 'Workouts',
    exercises: 'Exercises',
    progress: 'Progress',
    duration: 'Duration',
    calories: 'Calories',
    start: 'Start',
    complete: 'Complete',
    completed: 'Completed',
    inProgress: 'In Progress',
    myWorkouts: 'My Workouts',
    workoutPlans: 'Workout Plans',
    level: 'Level',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    category: 'Category',
    cardio: 'Cardio',
    strength: 'Strength',
    flexibility: 'Flexibility',
    yoga: 'Yoga',
    hiit: 'HIIT',
    weeklyProgress: 'Weekly Progress',
    totalWorkouts: 'Total Workouts',
    totalMinutes: 'Total minutes exercise',
    caloriesBurned: 'Calories Burned',
    caloriesIsBurned: 'Total calories burned',
    minutesExc: 'Minutes Practice',
    avgRating: 'Average Rating',
    avgScore: 'Average score',
    searchExc: '     Search for exercises...',
    weekgoal: 'This Week Goal',

    // Reminders
    medication: 'Medication',
    exercise: 'Exercise',
    bedtime: 'Sleep',
    time: 'Time',
    enabled: 'Enabled',
    disabled: 'Disabled',
    myReminders: 'My Reminders',
    upcomingReminders: 'Upcoming',
    pastReminders: 'Past',
    activeReminders: 'Active',
    reminderType: 'Reminder Type',
    reminderTime: 'Reminder Time',
    reminderMessage: 'Message',
    createReminder: 'Create Reminder',
    editReminder: 'Edit Reminder',
    deleteReminder: 'Delete Reminder',
    reminderTitle: 'Title',
    reminderDescription: 'Description',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    repeat: 'Repeat',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    never: 'Never',
    noReminder: 'There are no reminders for this day',
    general: 'General',
    allReminders: 'All Reminders',
    more: 'more',

    // Chatbot
    aiAssistant: 'AI Assistant',
    healthAssistant: 'Health Assistant',
    askMeAnything: 'Ask me anything',
    typeMessage: 'Type a message...',
    send: 'Send',
    quickQuestions: 'Quick Questions',
    chatHistory: 'Chat History',
    clearChat: 'Clear Chat',
    suggestedQuestions: 'Suggested Questions',
    noticalAI: 'AI may make mistakes. Please consult a doctor when necessary.',
    note1: 'How much cardio should I do each day?' ,
    note2: 'Suggest a reasonable medication schedule?',
    note3: 'What is a safe diet for weight loss?',
    note4: 'How can I improve my sleep quality?',

    // Profile
    personalInfo: 'Personal Information',
    healthInfo: 'Health Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    age: 'Age',
    gender: 'Gender',
    bloodGroup: 'Blood Group',
    height: 'Height',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    selectBloodGroup: 'Select Blood Group',
    enterHeight: 'Enter height',
    enterWeight: 'Enter weight',
    enterPhone: 'Enter phone',
    enterAddress: 'Enter address',
    active: 'Active',
    myProfile: 'My Profile',

    // Medical History
    medicalHistory: {
      title: 'Medical History',
      subtitle: 'Track and manage your medical records',
      listTitle: 'Medical Records List',
      addNew: 'Add New',
      addFirst: 'Add First Record',
      addTitle: 'Add New Medical Record',
      editTitle: 'Edit Medical Record',
      date: 'Date',
      day: 'Day',
      titleLabel: 'Title',
      notes: 'Notes',
      titlePlaceholder: 'e.g., Annual health checkup',
      notesPlaceholder: 'Describe your health condition, test results, medications...',
      cancel: 'Cancel',
      add: 'Add',
      update: 'Update',
      confirmDelete: 'Are you sure you want to delete this record?',
      noData: 'No medical records yet',
      total: 'Total',
      completed: 'Completed',
      ongoing: 'Ongoing',
      resolved: 'Resolved',
      unknown: 'Unknown',
      surgery: 'Surgery',
      checkup: 'Annual Health Checkup',
      vaccination: 'Flu Vaccination',
      headache: 'Persistent Headache',
      allergy: 'Seasonal Allergy',
      surgeryDetail: 'Appendectomy',
      checkupNotes: 'Annual health checkup results. All vital signs normal. Recommended to maintain current diet and exercise routine.',
      vaccinationNotes: 'Received 2024-2025 flu vaccination. No side effects. Need to repeat next year.',
      headacheNotes: 'Headache for 3 consecutive days. Took pain medication but no relief. Need further monitoring.',
      allergyNotes: 'Symptoms: sneezing, runny nose, itchy eyes. Used antihistamine medication. Avoid pollen exposure.',
      surgeryNotes: 'Laparoscopic appendectomy. Surgery successful. Recovery time: 2 weeks.',
      typeCheckup: 'Health Checkup',
      typeVaccination: 'Vaccination',
      typeSymptom: 'Symptom',
      typeAllergy: 'Allergy',
      typeSurgery: 'Surgery',
      typeOther: 'Other',
      viewAll: 'View Medical History'
    },

    // Settings
    appearance: 'Appearance',
    language: 'Language',
    notifications: 'Notifications',
    theme: 'Theme',
    lightMode: 'Light',
    darkMode: 'Dark',
    vietnamese: 'Vietnamese',
    english: 'English',
    themeDescription: 'Switch between light and dark mode',
    notificationPreferences: 'Notification Preferences',
    medicationReminders: 'Medication and exercise reminders',
    workoutNotifications: 'Workout completion',
    measurementNotifications: 'Health metrics updates',
    aiSuggestions: 'AI chatbot suggestions',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'Delete all your personal data. This action cannot be undone.',
    customizeExperience: 'Customize your experience',

    // Notifications
    notificationCenter: 'Notification Center',
    markAsRead: 'Mark as read',
    clearAll: 'Clear all',
    noNotifications: 'No notifications',
    yourActivitiesHere: 'Your activities will appear here',

    // Auth
    login: 'Login',
    signIn: 'Sign In',
    register: 'Register',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome Back',
    loginToContinue: 'Login to continue managing your health',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    joinHealthManager: 'Join Health Manager',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Remember me',
    enterEmail: 'Enter email',
    enterPassword: 'Enter password',
    enterFirstName: 'Enter first name',
    enterLastName: 'Enter last name',
    selectGender: 'Select Gender',
    // Registration validation
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    confirmPasswordRequired: 'Please confirm password',
    ageRequired: 'Age is required',
    genderRequired: 'Please select gender',
    invalidEmail: 'Invalid email address',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    ageMin: 'Age must be greater than 0',
    ageMax: 'Age must be less than 120',
    registrationSuccess: 'Registration successful!',
    registrationError: 'Registration error',
    // Social login
    orContinueWith: 'Or continue with',
    continueWithGoogle: 'Continue with Google',
    continueWithFacebook: 'Continue with Facebook',
    googleLoginComingSoon: 'Google login coming soon',
    facebookLoginComingSoon: 'Facebook login coming soon',

    deleteReminderConfirmation: 'Delete this reminder?',
    noUpcomingReminders: 'No upcoming reminders.',
    startDate: 'Start Date',
    endDate: 'End Date',
    editRecurringEventWarning: 'Note: Editing a recurring event will detach it from the series.',
    deleteRecurringReminderTitle: 'Delete Recurring Reminder',
    deleteRecurringReminderPrompt: 'Are you sure you want to delete the reminder',
    deleteAllOccurrences: 'Delete all occurrences',
    deleteThisOccurrenceOnly: 'Delete this occurrence only',

  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('vi');

  useEffect(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'en' || saved === 'vi') {
      setLanguage(saved);
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    const keys = key.split('.');
    let result = translations[language];

    for (const k of keys) {
      result = result?.[k];
    }

    return result || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
